#!/bin/sh

src="20:0"
dest="128:0"

while true; do
  res=$(aconnect -l)
  echo $res | grep "Connecting To: $dest" 2>&1 > /dev/null
  connected=$?

  if [ "$connected" -ne 0 ]; then
    echo ">>> not connected"
    aconnect $src $dest
  else
    #echo ">>> connected"
    true
  fi
  sleep 10
done
